-- Animal card state (deck, discard, pool, hands, boards) is managed entirely via BGA globals as JSON arrays.
-- Card IDs are 0-based indices into Material::ANIMAL_CARDS_DEFINITION; no SQL card table is needed.
